using FGScanner.DTOs;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using OfficeOpenXml.Table;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FGScanner.Services
{
    public sealed class InventoryCheckTagExcelService
    {
        public async Task<(bool isSuccess, string Message)> ExportAsync(
            IReadOnlyList<InventoryCheckTagData> tags,
            string filePath)
        {
            if (tags == null || tags.Count == 0)
            {
                return (false, "No inventory check tags are available to export.");
            }

            if (string.IsNullOrWhiteSpace(filePath))
            {
                return (false, "Please select an Excel output file.");
            }

            try
            {
                await Task.Run(() => CreateWorkbook(tags, filePath));
                return (true, $"Exported {tags.Count:N0} inventory check tags.");
            }
            catch (Exception ex)
            {
                return (false, $"Excel export failed: {ex.Message}");
            }
        }

        private static void CreateWorkbook(
            IReadOnlyList<InventoryCheckTagData> tags,
            string filePath)
        {
            ExcelPackage.License.SetNonCommercialPersonal("NIDEC");
            using var package = new ExcelPackage();
            ExcelWorksheet sheet = package.Workbook.Worksheets.Add("Inventory Count Tags");
            InventoryCheckTagData first = tags[0];

            package.Workbook.Properties.Title = "Inventory Count Tag Export";
            package.Workbook.Properties.Subject = "Month-end inventory count audit snapshot";
            package.Workbook.Properties.Author = "NIDEC Instruments (Philippines) Corporation";

            sheet.View.ShowGridLines = false;
            sheet.Cells.Style.Font.Name = "Arial";
            sheet.Cells.Style.Font.Size = 10;

            sheet.Cells[1, 1].Value = "INVENTORY COUNT TAG EXPORT";
            sheet.Cells[1, 1].Style.Font.Bold = true;
            sheet.Cells[1, 1].Style.Font.Size = 14;
            sheet.Cells[1, 1].Style.Font.Color.SetColor(Color.FromArgb(31, 78, 121));

            WriteMetadata(sheet, 2, 1, "Batch Code", first.BatchCode);
            WriteMetadata(sheet, 2, 4, "Cutoff Date", first.CutoffDate.ToDateTime(TimeOnly.MinValue));
            sheet.Cells[2, 5].Style.Numberformat.Format = "mm/dd/yyyy";
            WriteMetadata(sheet, 2, 7, "Warehouse", first.WarehouseId);
            WriteMetadata(sheet, 2, 10, "Generated By", first.GeneratedBy);
            WriteMetadata(sheet, 3, 1, "Exported Tags", tags.Count);
            WriteMetadata(sheet, 3, 4, "Exported At", DateTime.Now);
            sheet.Cells[3, 5].Style.Numberformat.Format = "mm/dd/yyyy hh:mm";

            string[] headers =
            {
                "Tag Number",
                "Batch Code",
                "Cutoff Date",
                "Warehouse",
                "ERP Location",
                "Rack Location",
                "Location Description",
                "Material Code",
                "Part Number",
                "Production Version",
                "Material Name",
                "Unit",
                "System Boxes",
                "System Quantity",
                "Physical Count",
                "Variance",
                "Remarks"
            };

            const int headerRow = 5;
            const int firstDataRow = headerRow + 1;
            for (int column = 0; column < headers.Length; column++)
            {
                sheet.Cells[headerRow, column + 1].Value = headers[column];
            }

            for (int index = 0; index < tags.Count; index++)
            {
                InventoryCheckTagData tag = tags[index];
                int row = firstDataRow + index;
                sheet.Cells[row, 1].Value = tag.TagNumber;
                sheet.Cells[row, 2].Value = tag.BatchCode;
                sheet.Cells[row, 3].Value = tag.CutoffDate.ToDateTime(TimeOnly.MinValue);
                sheet.Cells[row, 4].Value = tag.WarehouseId;
                sheet.Cells[row, 5].Value = tag.ErpLocation;
                sheet.Cells[row, 6].Value = tag.RackLocation;
                sheet.Cells[row, 7].Value = tag.LocationDescription;
                sheet.Cells[row, 8].Value = tag.MaterialCode;
                sheet.Cells[row, 9].Value = tag.PartNumber;
                sheet.Cells[row, 10].Value = tag.ProductionVersion;
                sheet.Cells[row, 11].Value = tag.MaterialName;
                sheet.Cells[row, 12].Value = tag.Unit;
                sheet.Cells[row, 13].Value = tag.SystemBoxes;
                sheet.Cells[row, 14].Value = tag.SystemQuantity;
                sheet.Cells[row, 15].Value = null;
                sheet.Cells[row, 16].Formula = $"IF(O{row}=\"\",\"\",O{row}-N{row})";
                sheet.Cells[row, 17].Value = null;
            }

            int lastRow = firstDataRow + tags.Count - 1;
            ExcelRange tableRange = sheet.Cells[headerRow, 1, lastRow, headers.Length];
            ExcelTable table = sheet.Tables.Add(tableRange, "InventoryCountTagsTable");
            table.TableStyle = TableStyles.Medium2;

            sheet.Cells[firstDataRow, 3, lastRow, 3].Style.Numberformat.Format = "mm/dd/yyyy";
            sheet.Cells[firstDataRow, 13, lastRow, 16].Style.Numberformat.Format = "#,##0";
            sheet.Cells[firstDataRow, 15, lastRow, 15].Style.Fill.PatternType = ExcelFillStyle.Solid;
            sheet.Cells[firstDataRow, 15, lastRow, 15].Style.Fill.BackgroundColor.SetColor(
                Color.FromArgb(255, 242, 204));
            sheet.Cells[firstDataRow, 16, lastRow, 16].Style.Fill.PatternType = ExcelFillStyle.Solid;
            sheet.Cells[firstDataRow, 16, lastRow, 16].Style.Fill.BackgroundColor.SetColor(
                Color.FromArgb(221, 235, 247));

            sheet.Cells[headerRow, 1, headerRow, headers.Length].Style.HorizontalAlignment =
                ExcelHorizontalAlignment.Center;
            sheet.Cells[headerRow, 1, lastRow, headers.Length].Style.VerticalAlignment =
                ExcelVerticalAlignment.Center;
            sheet.Cells[firstDataRow, 13, lastRow, 16].Style.HorizontalAlignment =
                ExcelHorizontalAlignment.Right;
            sheet.Cells[firstDataRow, 11, lastRow, 11].Style.WrapText = true;
            sheet.Cells[firstDataRow, 17, lastRow, 17].Style.WrapText = true;

            SetColumnWidths(sheet);
            sheet.View.FreezePanes(firstDataRow, 1);
            sheet.PrinterSettings.PaperSize = ePaperSize.A4;
            sheet.PrinterSettings.Orientation = eOrientation.Landscape;
            sheet.PrinterSettings.FitToPage = true;
            sheet.PrinterSettings.FitToWidth = 1;
            sheet.PrinterSettings.FitToHeight = 0;
            sheet.PrinterSettings.RepeatRows = sheet.Cells[headerRow, 1, headerRow, headers.Length];
            sheet.PrinterSettings.TopMargin = 0.4D;
            sheet.PrinterSettings.BottomMargin = 0.4D;
            sheet.PrinterSettings.LeftMargin = 0.25D;
            sheet.PrinterSettings.RightMargin = 0.25D;

            FileInfo output = new(filePath);
            output.Directory?.Create();
            package.SaveAs(output);
        }

        private static void WriteMetadata(
            ExcelWorksheet sheet,
            int row,
            int column,
            string label,
            object value)
        {
            sheet.Cells[row, column].Value = label;
            sheet.Cells[row, column].Style.Font.Bold = true;
            sheet.Cells[row, column].Style.Font.Color.SetColor(Color.FromArgb(89, 89, 89));
            sheet.Cells[row, column + 1].Value = value;
        }

        private static void SetColumnWidths(ExcelWorksheet sheet)
        {
            double[] widths =
            {
                16, 31, 12, 11, 14, 16, 18, 22, 20,
                16, 28, 8, 13, 15, 15, 13, 24
            };

            for (int index = 0; index < widths.Length; index++)
            {
                sheet.Column(index + 1).Width = widths[index];
            }
        }
    }
}
