using FGScanner.DTOs;
using FGScanner.Services;
using FGScanner.UI;
using System;
using System.Drawing;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace FGScanner.Forms.Reports
{
    public sealed class MonthEndCheckTagHistoryForm : Form
    {
        private readonly MonthEndCheckTagService _service;
        private readonly DataGridView _batches = new();
        private readonly Button _reprintButton = new();
        private readonly Label _status = new();

        public int SelectedBatchId { get; private set; }

        public MonthEndCheckTagHistoryForm(MonthEndCheckTagService service)
        {
            _service = service;
            InitializeUi();
            EnterpriseTheme.Apply(this);
            Shown += async (_, _) => await LoadBatchesAsync();
        }

        private void InitializeUi()
        {
            Text = "Saved Inventory Check-Tag Batches";
            StartPosition = FormStartPosition.CenterParent;
            ClientSize = new Size(940, 460);
            MinimizeBox = false;
            Font = new Font("Segoe UI", 9F);

            _status.Location = new Point(18, 14);
            _status.Size = new Size(650, 24);
            _status.Text = "Loading finalized batches...";

            _batches.Location = new Point(18, 44);
            _batches.Size = new Size(904, 350);
            _batches.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            _batches.ReadOnly = true;
            _batches.AllowUserToAddRows = false;
            _batches.AllowUserToDeleteRows = false;
            _batches.MultiSelect = false;
            _batches.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            _batches.AutoGenerateColumns = false;
            _batches.RowHeadersVisible = false;
            _batches.Columns.Add(CreateColumn("BatchCode", "Batch Code", 210));
            _batches.Columns.Add(CreateColumn("CutoffDate", "Cutoff", 90));
            _batches.Columns.Add(CreateColumn("Warehouse", "Warehouse", 80));
            _batches.Columns.Add(CreateColumn("Scope", "Scope", 130));
            _batches.Columns.Add(CreateColumn("Revision", "Revision", 65));
            _batches.Columns.Add(CreateColumn("TagCount", "Tags", 55));
            _batches.Columns.Add(CreateColumn("CreatedAt", "Generated At", 135));
            _batches.Columns.Add(CreateColumn("CreatedBy", "Generated By", 120));
            _batches.CellDoubleClick += (_, _) => SelectBatch();

            _reprintButton.Location = new Point(692, 408);
            _reprintButton.Size = new Size(120, 34);
            _reprintButton.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            _reprintButton.Text = "Reprint Selected";
            _reprintButton.Enabled = false;
            _reprintButton.Click += (_, _) => SelectBatch();

            var closeButton = new Button
            {
                DialogResult = DialogResult.Cancel,
                Location = new Point(822, 408),
                Size = new Size(100, 34),
                Anchor = AnchorStyles.Bottom | AnchorStyles.Right,
                Text = "Close"
            };

            Controls.Add(_status);
            Controls.Add(_batches);
            Controls.Add(_reprintButton);
            Controls.Add(closeButton);
            CancelButton = closeButton;
        }

        private static DataGridViewTextBoxColumn CreateColumn(
            string property,
            string header,
            int width) => new()
        {
            DataPropertyName = property,
            HeaderText = header,
            Width = width,
            SortMode = DataGridViewColumnSortMode.Automatic
        };

        private async Task LoadBatchesAsync()
        {
            try
            {
                var batches = await _service.ListBatchesAsync();
                _batches.DataSource = batches;
                _reprintButton.Enabled = batches.Count > 0;
                _status.Text = batches.Count == 0
                    ? "No finalized check-tag batches have been saved yet."
                    : $"{batches.Count:N0} saved batches. Double-click a row to reprint its original snapshot.";
            }
            catch (Exception ex)
            {
                _status.Text = "Unable to load saved batches.";
                MessageBox.Show(this, ex.Message, "Batch History", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void SelectBatch()
        {
            if (_batches.CurrentRow?.DataBoundItem is not InventoryCheckTagBatchSummary batch)
            {
                return;
            }

            SelectedBatchId = batch.BatchId;
            DialogResult = DialogResult.OK;
            Close();
        }
    }
}
